export const SingleShopItem = {
  id: 1,
  title: "Accessories",
  img: "images/Accessories/accessories.jpg",
  items: [
    {
      id: 1,
      title: "Grey backpack",
      img: "images/Accessories/Backpack.jpg",
      price: 20,
      inCart: false,
      count: 0,
      total: 0,
    },
    {
      id: 2,
      title: "Yellow backpack",
      img: "images/Accessories/Backpack-2.jpg",
      price: 25,
      inCart: false,
      count: 0,
      total: 0,
    },
    {
      id: 3,
      title: "Black backpack",
      img: "images/Accessories/Backpack-3.jpg",
      price: 32,
      inCart: false,
      count: 0,
      total: 0,
    },
    {
      id: 4,
      title: "Brown belt",
      img: "images/Accessories/Belt.jpg",
      price: 18,
      inCart: false,
      count: 0,
      total: 0,
    },
    {
      id: 5,
      title: "Black belt",
      img: "images/Accessories/Belt-2.jpg",
      price: 20,
      inCart: false,
      count: 0,
      total: 0,
    },
    {
      id: 6,
      title: "Leather belt",
      img: "images/Accessories/Belt-3.jpg",
      price: 22,
      inCart: false,
      count: 0,
      total: 0,
    },
    {
      id: 7,
      title: "Black wallet",
      img: "images/Accessories/Wallet.jpg",
      price: 15,
      inCart: false,
      count: 0,
      total: 0,
    },
    {
      id: 8,
      title: "Dark brown wallet",
      img: "images/Accessories/Wallet-2.jpg",
      price: 21,
      inCart: false,
      count: 0,
      total: 0,
    },
    {
      id: 9,
      title: "Brown wallet",
      img: "images/Accessories/Wallet-3.jpg",
      price: 25,
      inCart: false,
      count: 0,
      total: 0,
    },
    {
      id: 10,
      title: "Brown watch",
      img: "images/Accessories/Watch.jpg",
      price: 150,
      inCart: false,
      count: 0,
      total: 0,
    },
    {
      id: 11,
      title: "Black watch",
      img: "images/Accessories/Watch-2.jpg",
      price: 120,
      inCart: false,
      count: 0,
      total: 0,
    },
    {
      id: 12,
      title: "A&D watch",
      img: "images/Accessories/Watch-3.jpg",
      price: 220,
      inCart: false,
      count: 0,
      total: 0,
    },
  ],
};

export const ShopItems = [
  {
    id: 1,
    title: "Accessories",
    img: "images/Accessories/accessories.jpg",
    items: [
      {
        id: 1,
        title: "Grey backpack",
        img: "images/Accessories/Backpack.jpg",
        price: 20,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 2,
        title: "Yellow backpack",
        img: "images/Accessories/Backpack-2.jpg",
        price: 25,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 3,
        title: "Black backpack",
        img: "images/Accessories/Backpack-3.jpg",
        price: 32,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 4,
        title: "Brown belt",
        img: "images/Accessories/Belt.jpg",
        price: 18,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 5,
        title: "Black belt",
        img: "images/Accessories/Belt-2.jpg",
        price: 20,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 6,
        title: "Leather belt",
        img: "images/Accessories/Belt-3.jpg",
        price: 22,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 7,
        title: "Black wallet",
        img: "images/Accessories/Wallet.jpg",
        price: 15,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 8,
        title: "Dark brown wallet",
        img: "images/Accessories/Wallet-2.jpg",
        price: 21,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 9,
        title: "Brown wallet",
        img: "images/Accessories/Wallet-3.jpg",
        price: 25,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 10,
        title: "Brown watch",
        img: "images/Accessories/Watch.jpg",
        price: 150,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 11,
        title: "Black watch",
        img: "images/Accessories/Watch-2.jpg",
        price: 120,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 12,
        title: "A&D watch",
        img: "images/Accessories/Watch-3.jpg",
        price: 220,
        inCart: false,
        count: 0,
        total: 0,
      },
    ],
  },
  {
    id: 2,
    title: "Jackets",
    img: "images/Jackets/jacket.jpg",
    items: [
      {
        id: 13,
        title: "Grey jacket",
        img: "images/Jackets/jacket-1.jpg",
        price: 120,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 14,
        title: "Brown jacket",
        img: "images/Jackets/jacket-2.jpg",
        price: 125,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 15,
        title: "Blue jacket",
        img: "images/Jackets/jacket-3.jpg",
        price: 132,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 16,
        title: "Olive-V jacket",
        img: "images/Jackets/jacket-4.jpg",
        price: 118,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 17,
        title: "Dark blue jacket",
        img: "images/Jackets/jacket-5.jpg",
        price: 120,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 18,
        title: "Spring blue jacket",
        img: "images/Jackets/jacket-6.jpg",
        price: 122,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 19,
        title: "Light brown jacket",
        img: "images/Jackets/jacket-7.jpg",
        price: 115,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 20,
        title: "Light blue jacket",
        img: "images/Jackets/jacket-8.jpg",
        price: 121,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 21,
        title: "Brown-V jacket",
        img: "images/Jackets/jacket-9.jpg",
        price: 125,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 22,
        title: "B&B jacket",
        img: "images/Jackets/jacket-10.jpg",
        price: 150,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 23,
        title: "A-Ned jacket",
        img: "images/Jackets/jacket-11.jpg",
        price: 120,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 24,
        title: "Black jacket",
        img: "images/Jackets/jacket-12.jpg",
        price: 220,
        inCart: false,
        count: 0,
        total: 0,
      },
    ],
  },
  {
    id: 3,
    title: "Jeans",
    img: "images/Jeans/jeans.jpg",
    items: [
      {
        id: 25,
        title: "Light jeans",
        img: "images/Jeans/jeans-1.png",
        price: 120,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 26,
        title: "Blue jeans",
        img: "images/Jeans/jeans-2.jpg",
        price: 125,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 27,
        title: "Black jeans",
        img: "images/Jeans/jeans-3.jpg",
        price: 140,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 28,
        title: "light blue jeans",
        img: "images/Jeans/jeans-4.jpg",
        price: 100,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 29,
        title: "Light grey jeans",
        img: "images/Jeans/jeans-5.jpg",
        price: 90,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 30,
        title: "Dark blue jeans",
        img: "images/Jeans/jeans-6.png",
        price: 70,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 31,
        title: "Navi blue jeans",
        img: "images/Jeans/jeans-7.jpg",
        price: 150,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 32,
        title: "Blue-V2 jeans",
        img: "images/Jeans/jeans-8.jpg",
        price: 110,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 33,
        title: "Grey-S6 jeans",
        img: "images/Jeans/jeans-9.jpg",
        price: 125,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 34,
        title: "Black-L jeans",
        img: "images/Jeans/jeans-10.jpg",
        price: 90,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 35,
        title: "Hard dark jeans",
        img: "images/Jeans/jeans-11.jpg",
        price: 80,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 36,
        title: "A_black jeans",
        img: "images/Jeans/jeans12.jpg",
        price: 80,
        inCart: false,
        count: 0,
        total: 0,
      },
    ],
  },
  {
    id: 4,
    title: "Shirts",
    img: "images/Shirts/shirt.jpg",
    items: [
      {
        id: 37,
        title: "Spring shirt",
        img: "images/Shirts/shirt-1.jpg",
        price: 40,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 38,
        title: "Blue shirt",
        img: "images/Shirts/shirt-2.jpg",
        price: 45,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 39,
        title: "BGG shirt",
        img: "images/Shirts/shirt-3.jpg",
        price: 42,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 40,
        title: "Black shirt",
        img: "images/Shirts/shirt-4.jpg",
        price: 38,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 41,
        title: "Grey shirt",
        img: "images/Shirts/shirt-5.jpg",
        price: 20,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 42,
        title: "Blue-W shirt",
        img: "images/Shirts/shirt-6.jpg",
        price: 32,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 43,
        title: "BRW shirt",
        img: "images/Shirts/shirt-7.jpg",
        price: 35,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 44,
        title: "White shirt",
        img: "images/Shirts/shirt-8.jpg",
        price: 25,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 45,
        title: "Light grey shirt",
        img: "images/Shirts/shirt-9.jpg",
        price: 35,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 46,
        title: "E-color shirt",
        img: "images/Shirts/shirt-10.jpg",
        price: 50,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 47,
        title: "Blue pocket shirt",
        img: "images/Shirts/shirt-11.jpg",
        price: 20,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 48,
        title: "Black polo shirt",
        img: "images/Shirts/shirt-12.jpg",
        price: 20,
        inCart: false,
        count: 0,
        total: 0,
      },
    ],
  },
  {
    id: 5,
    title: "Hats",
    img: "images/Hats/Hats.jpg",
    items: [
      {
        id: 49,
        title: "Grey hat",
        img: "images/Hats/Hat.jpg",
        price: 20,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 50,
        title: "Red hat",
        img: "images/Hats/Hat-2.jpg",
        price: 25,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 51,
        title: "NY hat",
        img: "images/Hats/Hat-3.jpg",
        price: 32,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 52,
        title: "Grey-L Hat",
        img: "images/Hats/Hat-4.jpg",
        price: 18,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 53,
        title: "Old-fashion hat",
        img: "images/Hats/Hat-5.jpg",
        price: 20,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 54,
        title: "L&g hat",
        img: "images/Hats/Hat-6.jpg",
        price: 22,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 55,
        title: "Leather hat",
        img: "images/Hats/Hat-7.jpg",
        price: 15,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 56,
        title: "Yellow hat",
        img: "images/Hats/Hat-8.jpg",
        price: 10,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 57,
        title: "Black_N hat",
        img: "images/Hats/Hat-9.jpg",
        price: 25,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 58,
        title: "A-Niv hat",
        img: "images/Hats/Hat-10.jpg",
        price: 50,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 59,
        title: "b&b hat",
        img: "images/Hats/Hat-11.jpg",
        price: 20,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 60,
        title: "Light_B hat",
        img: "images/Hats/Hat-12.jpg",
        price: 20,
        inCart: false,
        count: 0,
        total: 0,
      },
    ],
  },
  {
    id: 6,
    title: "Sneakers",
    img: "images/Sneakers/sneakers.jpg",
    items: [
      {
        id: 61,
        title: "Black sneakers",
        img: "images/Sneakers/sneakers-1.jpg",
        price: 220,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 62,
        title: "Dark blue sneakers",
        img: "images/Sneakers/sneakers-2.jpg",
        price: 225,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 63,
        title: "Grey sneakers",
        img: "images/Sneakers/sneakers-3.jpg",
        price: 320,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 64,
        title: "Light grey sneakers",
        img: "images/Sneakers/sneakers-4.jpg",
        price: 180,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 65,
        title: "White sneakers",
        img: "images/Sneakers/sneakers-5.jpg",
        price: 200,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 66,
        title: "White_23 sneakers",
        img: "images/Sneakers/sneakers-6.jpg",
        price: 220,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 67,
        title: "Nav_blue sneakers",
        img: "images/Sneakers/sneakers-7.jpg",
        price: 150,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 68,
        title: "Black_White sneakers",
        img: "images/Sneakers/sneakers-8.jpg",
        price: 210,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 69,
        title: "Yellow sneakers",
        img: "images/Sneakers/sneakers-9.jpg",
        price: 250,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 70,
        title: "Navi_Gr sneakers",
        img: "images/Sneakers/sneakers-10.jpg",
        price: 150,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 71,
        title: "B_234 sneakers",
        img: "images/Sneakers/sneakers-11.jpg",
        price: 120,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 72,
        title: "A-270 sneakers",
        img: "images/Sneakers/sneakers-12.jpg",
        price: 220,
        inCart: false,
        count: 0,
        total: 0,
      },
    ],
  },
  {
    id: 7,
    title: "Suits",
    img: "images/Suits/suit.jpg",
    items: [
      {
        id: 73,
        title: "Nav-blue suit",
        img: "images/Suits/suit-1.jpg",
        price: 520,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 74,
        title: "Light-blue suit",
        img: "images/Suits/suit-2.jpg",
        price: 525,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 75,
        title: "Grey suit",
        img: "images/Suits/suit-3.jpg",
        price: 320,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 76,
        title: "Dark-brown suit",
        img: "images/Suits/suit-4.jpg",
        price: 180,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 77,
        title: "White suit",
        img: "images/Suits/suit-5.jpg",
        price: 420,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 78,
        title: "Blue suit",
        img: "images/Suits/suit-6.jpg",
        price: 220,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 79,
        title: "Blue-3 suit",
        img: "images/Suits/suit-7.jpg",
        price: 150,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 80,
        title: "Grey-3 suit",
        img: "images/Suits/suit-8.jpg",
        price: 210,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 81,
        title: "Grey-classic suit",
        img: "images/Suits/suit-9.jpg",
        price: 250,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 82,
        title: "Light-l5 suit",
        img: "images/Suits/suit-10.jpg",
        price: 150,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 83,
        title: "A-N suit",
        img: "images/Suits/suit-11.jpg",
        price: 120,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 84,
        title: "Mil-I suit",
        img: "images/Suits/suit-12.jpg",
        price: 220,
        inCart: false,
        count: 0,
        total: 0,
      },
    ],
  },
  {
    id: 8,
    title: "Ties",
    img: "images/Ties/tie.jpg",
    items: [
      {
        id: 85,
        title: "Aqua tie",
        img: "images/Ties/tie-1.jpg",
        price: 20,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 86,
        title: "Purple tie",
        img: "images/Ties/tie-2.jpg",
        price: 25,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 87,
        title: "Pink tie",
        img: "images/Ties/tie-3.jpg",
        price: 30,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 88,
        title: "Stripes tie",
        img: "images/Ties/tie-4.jpg",
        price: 50,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 89,
        title: "Dark blue tie",
        img: "images/Ties/tie-5.jpg",
        price: 40,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 90,
        title: "Light blue tie",
        img: "images/Ties/tie-6.jpg",
        price: 25,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 91,
        title: "Blue tie",
        img: "images/Ties/tie-7.jpg",
        price: 35,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 92,
        title: "Pink-A6 tie",
        img: "images/Ties/tie-8.jpg",
        price: 25,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 93,
        title: "Blue-D tie",
        img: "images/Ties/tie-9.jpg",
        price: 25,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 94,
        title: "Gold tie",
        img: "images/Ties/tie-10.jpg",
        price: 50,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 95,
        title: "Grey tie",
        img: "images/Ties/tie-11.jpg",
        price: 20,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 96,
        title: "V&N tie",
        img: "images/Ties/tie-12.jpg",
        price: 20,
        inCart: false,
        count: 0,
        total: 0,
      },
    ],
  },
  {
    id: 9,
    title: "Trousers",
    img: "images/Trousers/trousers.jpg",
    items: [
      {
        id: 97,
        title: "White trousers",
        img: "images/Trousers/trousers-1.jpg",
        price: 120,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 98,
        title: "Fan-G trousers",
        img: "images/Trousers/trousers-2.jpg",
        price: 90,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 99,
        title: "Grey trousers",
        img: "images/Trousers/trousers-3.jpg",
        price: 100,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 100,
        title: "Light brown trousers",
        img: "images/Trousers/trousers-4.png",
        price: 180,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 101,
        title: "Dark blue trousers",
        img: "images/Trousers/trousers-5.jpg",
        price: 200,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 102,
        title: "Light blue trousers",
        img: "images/Trousers/trousers-6.jpg",
        price: 220,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 103,
        title: "Light trousers",
        img: "images/Trousers/trousers-7.jpg",
        price: 150,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 104,
        title: "Dark grey trousers",
        img: "images/Trousers/trousers-8.jpg",
        price: 130,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 105,
        title: "A&N trousers",
        img: "images/Trousers/trousers-9.jpg",
        price: 125,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 106,
        title: "Dark brown trousers",
        img: "images/Trousers/trousers-10.jpg",
        price: 150,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 107,
        title: "B-2020 trousers",
        img: "images/Trousers/trousers-11.jpg",
        price: 120,
        inCart: false,
        count: 0,
        total: 0,
      },
      {
        id: 108,
        title: "Blue-parish trousers",
        img: "images/Trousers/trousers-12.jpg",
        price: 120,
        inCart: false,
        count: 0,
        total: 0,
      },
    ],
  },
];
